// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzphblbziakzhbekpqit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6cGhibGJ6aWFremhiZWtwcWl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyODcyMjgsImV4cCI6MjA2NDg2MzIyOH0.DTZF0w_h8QwG-G190MUPcPRN0bmubeBLRXOqdpJw_N8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
